
package com.handson.jaxbjaxws.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PurchaseOrderWS", targetNamespace = "http://service.jaxbjaxws.handson.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PurchaseOrderWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addOrder", targetNamespace = "http://service.jaxbjaxws.handson.com/", className = "com.handson.jaxbjaxws.service.AddOrder")
    @ResponseWrapper(localName = "addOrderResponse", targetNamespace = "http://service.jaxbjaxws.handson.com/", className = "com.handson.jaxbjaxws.service.AddOrderResponse")
    @Action(input = "http://service.jaxbjaxws.handson.com/PurchaseOrderWS/addOrderRequest", output = "http://service.jaxbjaxws.handson.com/PurchaseOrderWS/addOrderResponse")
    public long addOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        PurchaseOrder arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.handson.jaxbjaxws.service.PurchaseOrder>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllOrders", targetNamespace = "http://service.jaxbjaxws.handson.com/", className = "com.handson.jaxbjaxws.service.GetAllOrders")
    @ResponseWrapper(localName = "getAllOrdersResponse", targetNamespace = "http://service.jaxbjaxws.handson.com/", className = "com.handson.jaxbjaxws.service.GetAllOrdersResponse")
    @Action(input = "http://service.jaxbjaxws.handson.com/PurchaseOrderWS/getAllOrdersRequest", output = "http://service.jaxbjaxws.handson.com/PurchaseOrderWS/getAllOrdersResponse")
    public List<PurchaseOrder> getAllOrders();

}
